### ISSUE TITLE
Chat bottom cut off

### ISSUE THREAD

**Issue by lolapus** [brian91292/EnhancedStreamChat-v3#15]
I don't know if this has been reported already but the bottom of the chat is cut off.

**Comment by brian91292** [comment]
A screenshot or video showing the issue would be great.

**Comment by lolapus** [comment]
When I went to grab a screenshot the problem seemed to have gone away. I'm sorry for wasting your time, you can close the issue

**Comment by brian91292** [comment]
If it happens again and you can get a screenshot or more details, feel free to respond here and I'll reopen it.
