### ISSUE TITLE
Should i Post here or in Mod Discord?

### ISSUE THREAD

**Issue by 2ToneSig** [brian91292/EnhancedStreamChat-v3#2]
Setup and initial config work great, chat is running and works on initial start. When I close BS and then reopen, the chat window doesn't show up, and i do not get the browser config window.

**Comment by brian91292** [comment]
Thanks for the report, looks like an issue with old config conversion if StreamCore is still installed. To resolve it, delete StreamCore.dll and StreamCore.manifest from your plugins folder in Beat Saber, then remove TwitchLoginInfo.ini from The UserData/StreamCore folder in your Beat Saber directory. 

Will post a fix later.
