### ISSUE TITLE
1.12.2 - Beat Saber Update?

### ISSUE THREAD

**Issue by richardszanyi** [brian91292/EnhancedStreamChat-v3#25]
Hi, 

Firstly, I appreciate the effort you put into this mod, and ChatCore. 

Second, is there any plan to update the mod to 1.12.2 version of Beat Saber? Currently there is no way to put the chat inside Beat Saber, and that would be really cool. 

Cheers, and take care

**Comment by brian91292** [comment]
I am no longer maintaining this mod. Keep an eye on beatmods for the upload, or Eris' fork of the mod: https://github.com/ErisApps/EnhancedStreamChat-v3
