### ISSUE TITLE
Cyrillic characters are not displayed correctly

### ISSUE THREAD

**Issue by approxima** [brian91292/EnhancedStreamChat-v3#3]
Hi! The in-game chat works well with Latin characters, but Cyrillic are not displayed properly (?????? instead).

**Comment by brian91292** [comment]
Pretty weird, [this is the font I'm using](https://fonts.google.com/specimen/Noto+Sans) for the chat, and it says it should support Cyrillic characters. This issue will be resolved soon enough as I'm going to be moving to another font solution that will allow you to select a system font again.
