### ISSUE TITLE
Dropping in EnhancedStreamChat.dll won't appear on in-game screen

### ISSUE THREAD

**Issue by LegionHeir** [brian91292/EnhancedStreamChat-v3#7]
I downloaded this new version of enhanced stream chat and added it into my plugins folder as well as streamcore and filled in all the twitchlogininfo but the twitch chat doesn't appear overhead in the game. Is this the correct version I need in order to make twitchchat to appear or am I missing a step? I also just replaced this version with the dll file from https://github.com/benneeh/EnhancedStreamChat/releases/tag/2.2.1 and my twitch chat appears. The only difference I can see is that when I added Benneed version I saw EnhancedStreamChat (Config Setting file) being created in Userdata/Streamcore/. Is EnhancedStreamChat-v3 only used in tandem with Chatcore? I get this is still a WIP but I just wanted to know any info in regards to this.

**Comment by brian91292** [comment]
Yes, it can only be used with ChatCore. Once this new version of EnhancedStreamChat/ChatCore get pushed to Beat Mods, the mods that utilized StreamCore will be updated accordingly.

**Comment by brian91292** [comment]
If you still need help with the configuration, check out this link:
https://github.com/brian91292/EnhancedStreamChat-v3#basic-configuration-for-users

**Comment by LegionHeir** [comment]
Thank you for the explanation! I didn't understand that was the case seeing how enhancedstreamchat was separate. But this clears up everything so again thanks. I'll look into the link.
