### ISSUE TITLE
chat panel content tilted

### ISSUE THREAD

**Issue by OoDeeR** [brian91292/EnhancedStreamChat-v3#9]
The entire content of the panel is tilted.
The main issue is illustrated in these clips:
https://clips.twitch.tv/DiligentWealthyRedpandaOMGScoots
https://clips.twitch.tv/ColdbloodedAmazingCheetahBrokeBack

tilting the window and restarting seems to have an effect, not always a desired one, since you can make the cogwheel inaccessible...
Not sure if related, but for completeness: upon the first game start after installing ESC-v3 and ChatCore, I still had StreamCore installed at the same time, which lead to some additional issues with the chat display(subscriber badges were going to the end of the line instead of the front). After removing StreamCore, the general appearance of the chat was fine, just tilted.
[2020.06.17.12.18.26.log](https://github.com/brian91292/EnhancedStreamChat-v3/files/4793347/2020.06.17.12.18.26.log)

**Comment by brian91292** [comment]
Thanks for reminding me about the other issue as well, I forgot about the settings cog being inaccessible. Will look into that later this week.

**Comment by brian91292** [comment]
This has been resolved, so I'll close this issue now.
